#!/bin/bash
# Move all measurement files to archive

#to mark script executable:
#   chmod +x file


read -p "Move all measurement files to achive directory? [y/n] " -n 1 -r 
echo 

if [[ $REPLY =~ ^[Yy]$ ]]
then
    mv measurements/*.csv measurements/archive/
fi
