#!/bin/bash
# Remove (clear) all measurements

#to mark script executable:
#   chmod +x file


read -p "Remove all measurement files? [y/n] " -n 1 -r 
echo 

if [[ $REPLY =~ ^[Yy]$ ]]
then
    rm measurements/*
fi
